# Site Settings
title: My Resume
url: 'burakakde.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Burak Akdemir
tagline: B.Sc & M.Sc
pic: vesikalik_100x100.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I have graduated from Middle East Technical University Northern Cyprus Campus (METU NCC) Electrical And Electronics Engineering department.
In my undergraduate years I acquired two honor and one high honor certificates.
In addition, I was board Member of "METU NCC Young Entrepreneurs Society" and had two internships one in ASELSAN (6 weeks) and one in TAI (4 weeks).
I also had the chance to be an Erasmus exchange student at "Technical University of Munich".
When I was back in my home university, I worked as Assistant Student for "Signals & Systems I" course.
In my final year, I took the course "Fundamental Image Processing Techniques(AA)".
With this course my interest towards image processing/computer vision has flourished.
<br> <br>
After graduation, I decided to enhance my skills in image processing/computer vision discipline.
As a result I applied to KU Leuven (Ranked as 40. in World University Rankings 2016-2017 by times higher education) for master degree and get accepted.
In my master studies in Belgium I took 27 courses which include 
<br>
Digital Signal Processing for Communications and Information Systems (AA)<br> 
Data Mining (BA) <br>
Bio-Informatics (BA) <br>
Artificial Neural Networks (BB).<br>

I have also written my masters thesis, Autonomous Flight for a Quadrotor using Single Image Based Obstacle Avoidance, in the related field. The aim of my thesis was to design a system that prevents the drones from crashing into obstacles by estimating the depth from a single image. Fundamental concepts like SVM, CNN, etc... are used (more information available upon request).
<br><br>
The projects I have participated in are mainly written in C, C++ and Matlab. The tools I worked with include but not limited to Xilinx, Pspice, LabVIEW, etc...'

#sidebar links
email: burakakde@gmail.com
#phone: 012 345 6789
website: burakakde.com #do not add http://
#linkedin: alandoe
github: burakakde
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
