# Site Settings
title: My Resume
url: 'burakakde.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Burak Akdemir
tagline: B.Sc & M.Sc
pic: vesikalik_100x100.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I have graduated from Middle East Technical University Northern Cyprus Campus (METU NCC) Electrical And Electronics Engineering department.'

#sidebar links
email: burakakde@gmail.com
#phone: 012 345 6789
website: burakakde.com #do not add http://
#linkedin: alandoe
github: burakakde
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
